### ISSUE TITLE
Spelling mistake on webpage 'FEEDOM'

### ISSUE THREAD

**Issue by superrad** [silexlabs/www.silex.me#26]
'Freedom' is misspelled as 'Feedom' on the home page

**Comment by lexoyo** [comment]
Oooooh nice catch !!!
Thank you for the report. Would you consider fixing it yourself? The website is editable with Silex by anybody, I can help you get it done... Are you hot or not ;))

**Comment by gunnaraas** [comment]
@superrad I just made some pull requests fixing this. Once they're approved, you should be all set to close this report.

**Comment by lexoyo** [comment]
Great, thank you !
